sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: 改成自己数据库
    username: 改成自己账号
    password: 改成自己密码
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 有阿里云OSS才填，没有留空即可
    access-key-secret: 有阿里云OSS才填，没有留空即可
    bucket-name: 有阿里云OSS才填，没有留空即可
  jwt:
    admin-secret-key: itcast
    admin-ttl: 14400000
    admin-token-name: token
    user-secret-key: itcast
    user-token-name: token
    user-ttl: 14400000


spring:
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  reasonable: true

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
